package ccsd.pseudo;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface NativeBridgeConstants {
  // enums and constants
  public final static int QUANTITY_UNKNOWN = NativeBridgeJNI.get_QUANTITY_UNKNOWN();
  public final static int QUANTITY_TEMPERATURE = NativeBridgeJNI.get_QUANTITY_TEMPERATURE();
  public final static int QUANTITY_TEMPERATURE_WAND = NativeBridgeJNI.get_QUANTITY_TEMPERATURE_WAND();
  public final static int QUANTITY_LIGHT = NativeBridgeJNI.get_QUANTITY_LIGHT();
  public final static int QUANTITY_GAS_PRESSURE = NativeBridgeJNI.get_QUANTITY_GAS_PRESSURE();
  public final static int QUANTITY_VOLTAGE = NativeBridgeJNI.get_QUANTITY_VOLTAGE();
  public final static int QUANTITY_FORCE = NativeBridgeJNI.get_QUANTITY_FORCE();
  public final static int QUANTITY_VELOCITY = NativeBridgeJNI.get_QUANTITY_VELOCITY();
  public final static int QUANTITY_RELATIVE_HUMIDITY = NativeBridgeJNI.get_QUANTITY_RELATIVE_HUMIDITY();
  public final static int QUANTITY_ACCELERATION = NativeBridgeJNI.get_QUANTITY_ACCELERATION();
  public final static int QUANTITY_PULSE_RATE = NativeBridgeJNI.get_QUANTITY_PULSE_RATE();
  public final static int QUANTITY_CURRENT = NativeBridgeJNI.get_QUANTITY_CURRENT();
  public final static int QUANTITY_POWER = NativeBridgeJNI.get_QUANTITY_POWER();
  public final static int QUANTITY_ENERGY = NativeBridgeJNI.get_QUANTITY_ENERGY();
  public final static int QUANTITY_DISTANCE = NativeBridgeJNI.get_QUANTITY_DISTANCE();
  public final static int QUANTITY_SOUND_INTENSITY = NativeBridgeJNI.get_QUANTITY_SOUND_INTENSITY();
  public final static int QUANTITY_COMPASS = NativeBridgeJNI.get_QUANTITY_COMPASS();
  public final static int QUANTITY_ANGULAR_VELOCITY = NativeBridgeJNI.get_QUANTITY_ANGULAR_VELOCITY();
  public final static int QUANTITY_WIND_SPEED = NativeBridgeJNI.get_QUANTITY_WIND_SPEED();
}
