/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif


#if defined(__GNUC__)
    typedef long long __int64; /*For gcc on Windows */
#endif
#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "windows.h"
#include "FTD2XX.h"

typedef struct {
	FT_HANDLE handle;
	FT_STATUS status;
} FTClassicPort;


#if defined(SWIG_NOINCLUDE) || defined(SWIG_NOARRAYS)


int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input);
void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input);
jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz);


int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input);
void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input);
jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz);


int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input);
void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input);
jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz);


int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input);
void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input);
jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz);


int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input);
void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input);
jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz);


int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input);
void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input);
jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz);


int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input);
void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input);
jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz);


int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input);
void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input);
jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz);


int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input);
void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input);
jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz);


int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input);
void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input);
jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz);


int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input);
void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input);
jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz);


#else


/* signed char[] support */
int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetByteArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (signed char*) calloc(sz, sizeof(signed char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (signed char)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jbyte)carr[i];
  (*jenv)->ReleaseByteArrayElements(jenv, input, jarr, 0);
}

jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz) {
  jbyte *arr;
  int i;
  jbyteArray jresult = (*jenv)->NewByteArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetByteArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jbyte)result[i];
  (*jenv)->ReleaseByteArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned char[] support */
int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned char*) calloc(sz, sizeof(unsigned char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned char)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* short[] support */
int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (short*) calloc(sz, sizeof(short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (short)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned short[] support */
int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned short*) calloc(sz, sizeof(unsigned short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned short)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* int[] support */
int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (int*) calloc(sz, sizeof(int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (int)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned int[] support */
int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned int*) calloc(sz, sizeof(unsigned int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned int)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* long[] support */
int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (long*) calloc(sz, sizeof(long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (long)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned long[] support */
int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned long*) calloc(sz, sizeof(unsigned long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned long)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* jlong[] support */
int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (jlong*) calloc(sz, sizeof(jlong)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (jlong)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* float[] support */
int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetFloatArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (float*) calloc(sz, sizeof(float)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (float)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jfloat)carr[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, input, jarr, 0);
}

jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz) {
  jfloat *arr;
  int i;
  jfloatArray jresult = (*jenv)->NewFloatArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetFloatArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jfloat)result[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* double[] support */
int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetDoubleArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (double*) calloc(sz, sizeof(double)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (double)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jdouble)carr[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, input, jarr, 0);
}

jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz) {
  jdouble *arr;
  int i;
  jdoubleArray jresult = (*jenv)->NewDoubleArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetDoubleArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jdouble)result[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


#endif

static void FTClassicPort_open(FTClassicPort *self,int deviceNumber){
	self->status = FT_Open(deviceNumber, &(self->handle));
}
static void FTClassicPort_close(FTClassicPort *self){
	self->status =  FT_Close(self->handle);
}
static DWORD FTClassicPort_read(FTClassicPort *self,LPVOID lpBuffer,DWORD nBufferSize){
	DWORD output;
	self->status = FT_Read(self->handle, lpBuffer, nBufferSize,
		&output);
	return output;		
}
static DWORD FTClassicPort_write(FTClassicPort *self,LPVOID lpBuffer,DWORD nBufferSize){
	DWORD output;
	self->status = FT_Write(self->handle, lpBuffer, nBufferSize,
		&output);
	return output;
}
static void FTClassicPort_setBaudRate(FTClassicPort *self,ULONG BaudRate){
	self->status = FT_SetBaudRate(self->handle, BaudRate);
}
static void FTClassicPort_setDataCharacteristics(FTClassicPort *self,UCHAR WordLength,UCHAR StopBits,UCHAR Parity){
	self->status = FT_SetDataCharacteristics(self->handle, WordLength,
		StopBits, Parity);
}
static void FTClassicPort_setFlowControl(FTClassicPort *self,USHORT FlowControl,UCHAR XonChar,UCHAR XoffChar){
	self->status = FT_SetFlowControl(self->handle, FlowControl,
		XonChar, XoffChar);
}
static void FTClassicPort_resetDevice(FTClassicPort *self){
	self->status = FT_ResetDevice(self->handle);
}
static void FTClassicPort_setDtr(FTClassicPort *self){
    self->status = FT_SetDtr(self->handle);
}
static void FTClassicPort_clrDtr(FTClassicPort *self){
	self->status = FT_ClrDtr(self->handle);
}
static void FTClassicPort_setRts(FTClassicPort *self){
	self->status = FT_SetRts(self->handle);
}
static void FTClassicPort_crRts(FTClassicPort *self){
	self->status = FT_ClrRts(self->handle);
}
static void FTClassicPort_setTimeouts(FTClassicPort *self,ULONG ReadTimeout,ULONG WriteTimeout){
	self->status = FT_SetTimeouts(self->handle,
		ReadTimeout, WriteTimeout);		
}
static void FTClassicPort_resetPort(FTClassicPort *self){
	self->status = FT_ResetPort(self->handle);
}

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_set_1FTClassicPort_1handle(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    FT_HANDLE arg2 = (FT_HANDLE) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    arg2 = *(FT_HANDLE *)&jarg2; 
    if (arg1) (arg1)->handle = arg2;
    
}


JNIEXPORT jlong JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_get_1FTClassicPort_1handle(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    FT_HANDLE result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    result = (FT_HANDLE) ((arg1)->handle);
    
    *(FT_HANDLE *)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_set_1FTClassicPort_1status(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    FT_STATUS arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    arg2 = (FT_STATUS)jarg2; 
    if (arg1) (arg1)->status = arg2;
    
}


JNIEXPORT jlong JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_get_1FTClassicPort_1status(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    FT_STATUS result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    result = (FT_STATUS) ((arg1)->status);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1open(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    int arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    arg2 = (int)jarg2; 
    {
        FTClassicPort_open(arg1,arg2);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1close(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    {
        FTClassicPort_close(arg1);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT jlong JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jbyteArray jarg2, jlong jarg3) {
    jlong jresult = 0 ;
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    LPVOID arg2 = (LPVOID) 0 ;
    DWORD arg3 ;
    DWORD result;
    jbyte *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    if (!SWIG_JavaArrayInSchar(jenv, &jarr2, &arg2, jarg2)) return 0; 
    arg3 = (DWORD)jarg3; 
    {
        result = (DWORD)FTClassicPort_read(arg1,arg2,arg3);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return 0;
        }
    }
    jresult = (jlong)result; 
    SWIG_JavaArrayArgoutSchar(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jbyteArray jarg2, jlong jarg3) {
    jlong jresult = 0 ;
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    LPVOID arg2 = (LPVOID) 0 ;
    DWORD arg3 ;
    DWORD result;
    jbyte *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    if (!SWIG_JavaArrayInSchar(jenv, &jarr2, &arg2, jarg2)) return 0; 
    arg3 = (DWORD)jarg3; 
    {
        result = (DWORD)FTClassicPort_write(arg1,arg2,arg3);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return 0;
        }
    }
    jresult = (jlong)result; 
    SWIG_JavaArrayArgoutSchar(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
    return jresult;
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1setBaudRate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    ULONG arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    arg2 = (ULONG)jarg2; 
    {
        FTClassicPort_setBaudRate(arg1,arg2);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1setDataCharacteristics(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jshort jarg3, jshort jarg4) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    UCHAR arg2 ;
    UCHAR arg3 ;
    UCHAR arg4 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    arg2 = (UCHAR)jarg2; 
    arg3 = (UCHAR)jarg3; 
    arg4 = (UCHAR)jarg4; 
    {
        FTClassicPort_setDataCharacteristics(arg1,arg2,arg3,arg4);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1setFlowControl(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jshort jarg3, jshort jarg4) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    USHORT arg2 ;
    UCHAR arg3 ;
    UCHAR arg4 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    arg2 = (USHORT)jarg2; 
    arg3 = (UCHAR)jarg3; 
    arg4 = (UCHAR)jarg4; 
    {
        FTClassicPort_setFlowControl(arg1,arg2,arg3,arg4);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1resetDevice(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    {
        FTClassicPort_resetDevice(arg1);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1setDtr(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    {
        FTClassicPort_setDtr(arg1);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1clrDtr(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    {
        FTClassicPort_clrDtr(arg1);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1setRts(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    {
        FTClassicPort_setRts(arg1);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1crRts(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    {
        FTClassicPort_crRts(arg1);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1setTimeouts(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    ULONG arg2 ;
    ULONG arg3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    arg2 = (ULONG)jarg2; 
    arg3 = (ULONG)jarg3; 
    {
        FTClassicPort_setTimeouts(arg1,arg2,arg3);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_FTClassicPort_1resetPort(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    {
        FTClassicPort_resetPort(arg1);
        
        if(arg1->status != FT_OK){
            jclass clazz = (*jenv)->FindClass(jenv, "java/io/IOException");
            (*jenv)->ThrowNew(jenv, clazz, "IOException");
            return ;
        }
    }
}


JNIEXPORT jlong JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_new_1FTClassicPort(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    FTClassicPort *result;
    
    (void)jenv;
    (void)jcls;
    result = (FTClassicPort *)(FTClassicPort *) calloc(1, sizeof(FTClassicPort));
    
    *(FTClassicPort **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_org_concord_ftdi_FtdiSerialWrapperJNI_delete_1FTClassicPort(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    FTClassicPort *arg1 = (FTClassicPort *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FTClassicPort **)&jarg1; 
    free((char *) arg1);
    
}


#ifdef __cplusplus
}
#endif

